jobs:
- job: CI
  strategy:
    maxParallel: 2
    matrix:
      Linux:
        vmImage: ubuntu-16.04
      Windows:
        vmImage: vs2017-win2016
  steps:
    - script: |
        yarn install
        yarn test
      